### ISSUE TITLE
Clinical Statements - Edit button missing

### ISSUE THREAD

**Issue by BogdanScherban** [PulseTile/Showcase-Project#1]
Edit button should be present in Clinical Statements

**Comment by BogdanScherban** [comment]
Edit button is absent, but request for editing absent too. Do we have possibility to edit Clinical Statements at server path? 

If we have what URL should be?

We need in Rob's answer.

**Comment by tony-shannon** [comment]
On exploring the related codebase it appears there are GETs, POSTs but no PUT to support editing
https://github.com/RippleOSI/Ripple-Qewd/blob/3b0e3d27abd76a90e1cdb579104b02ae0914fe85/lib/api.js
.. cant recall rationale, but lets close this for now until the issue rearises
T
