### ISSUE TITLE
setup PulseTile RA & QewdC on showcase-dev

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/Showcase-Project#12]
to do please

**Comment by tony-shannon** [comment]
PulseTile RA components to add;

- Charts
- MPV
- Problems
- Meds
- Allergy
- Vaccinaations
- Top 3 things
- Respect
- Feeds

**Comment by PhilBarrett** [comment]
See showcase-devra.ripple.foundation:8080

**Comment by kuvakina** [comment]
> See showcase-devra.ripple.foundation 

@PhilBarrett it's not working yet, correct?

**Comment by PhilBarrett** [comment]
@kuvakina  see showcase-devra.ripple.foundation:8080

Working fine. moving to closed
