### ISSUE TITLE
Basic theme for showcase stack login

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/Showcase-Project#13]

**Comment by tony-shannon** [comment]
currently the latest Ripple stack enforces OIDC (fair enough)
but the OIDC page has Helm login branding we need simpler clean version for Ripple stack

**Comment by simongamester** [comment]
@tony-shannon How would you like me to deliver this? We have a repo containing a static html version of the login screen, which Rob has previously used as a template which he copy / pastes on to the server. 

https://github.com/PulseTile-Plugins/Plugin-UserLogin_Theme-HelmPHR

Would you like me to submit a copy of that to this repo with branding elements stripped out?

**Comment by simongamester** [comment]
I've set up a version for NES in the following Repo.

https://github.com/simongamester/UserLogin_Theme-NES

**Comment by simongamester** [comment]
Apologies, added this to the wrong issue. Please disregard.

**Comment by simongamester** [comment]
@tony-shannon @PhilBarrett I've set up a new repo containing the static files for this. They can be found here:

https://github.com/simongamester/UserLogin_Theme-Showcase

**Comment by tony-shannon** [comment]
thanks @simongamester 

FYI @kuvakina  and @BogdanScherban  please plan to update the PulseTile RA work for showcase with this, thanks

**Comment by tony-shannon** [comment]
BTW our repos need to be updated with these changes, please confirm that before closing this issue

**Comment by PhilBarrett** [comment]
@tony-shannon  WDYT re background image https://pixabay.com/photos/santiago-calatrava-architecture-1548506/

**Comment by PhilBarrett** [comment]
@kuvakina see #22, we are going to have logins for the showcase

**Comment by kuvakina** [comment]
@PhilBarrett @tony-shannon 
Could you please specify what Bogdan should do here? Or first, we are waiting for Dima's changes with Auth0?

**Comment by PhilBarrett** [comment]
> https://github.com/simongamester/UserLogin_Theme-Showcase

@kuvakina please see simon's message above. We are looking for a clean login screen for Showcase RA. Much as per One London, but this time with Auth0 and the image below. If you prefer to wait until Dima has completed his tasks no worries, I'll add the dependency in

> @tony-shannon WDYT re background image https://pixabay.com/photos/santiago-calatrava-architecture-1548506/

**Comment by DmitrySolyannik** [comment]
@tony-shannon , @PhilBarrett , @kuvakina, @BogdanScherban 
I've checked this login changes, but one problem, we are using ejs file with some logic on login page (OpenID MS). Here is what we are using right now on showcase. 
https://github.com/QEWD-Courier/QEWD-Courier/blob/develop/oidc_provider/openid-connect-server/modules/qewd-openid-connect/lib/views/login.ejs

This html from @simongamester, should be changed to ejs and also need to add login functionality

**Comment by simongamester** [comment]
Hi @DmitrySolyannik 

I'll update my repo at https://github.com/simongamester/UserLogin_Theme-Showcase and provide an ejs version of the index.html file in there which pulls in the logic from the login.ejs file above.

I don't have any way of testing the code in the ejs, so you may need to test this before deploying.

**Comment by kuvakina** [comment]
@PhilBarrett  @tony-shannon 

We added User login with Showcase-theme:
![11111111111111111111.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/537731d0-cd5c-45b7-9104-b050d247b78b)

Can we close this task?

**Comment by PhilBarrett** [comment]
Reviewed, closing
