### ISSUE TITLE
Change login page for Showcase to generic for future projects

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#14]
Including NES and showcase?

@simongamester, please could you mockup a plain non NHS, non helm wireframe please.

**Comment by simongamester** [comment]
I've mocked up the static html for the login screen for NES. 
See index.html from the following repo:
https://github.com/simongamester/UserLogin_Theme-NES

**Comment by tony-shannon** [comment]
I've updated related issue on NES project
https://waffle.io/RippleOSI/combined-development-view/cards/5c8b8831e09d4200a83ed84d

https://github.com/RippleOSI/NHS_Ed_Scotland_Open_Platform/issues/52

**Comment by tony-shannon** [comment]
Showcase still needs new login page, with Ripple Logo please

**Comment by tony-shannon** [comment]
the Showcase login has been updated by @simongamester  thanks
Link & update available in this linked issue  here
https://github.com/RippleOSI/Ripple-Showcase-Stack-Project/issues/13

https://waffle.io/RippleOSI/combined-development-view/cards/5c7f9cd2b9ba6c0314cab6aa
