### ISSUE TITLE
React-Admin Showcase Stack - Vital signs 

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#19]
refactoring of React vital signs to React-Admin

http://docs.pulsetile.com/react-vitals.html

**Comment by kuvakina** [comment]
@PhilBarrett @tony-shannon 

Bogdan started a work on it, and he can tell that approx work on Vitals would take 10 -16h. We'll try to make it faster, but for this issue and for Transfer of Care ( #20 )  , he needs server-side functionality to test it

**Comment by tony-shannon** [comment]
Bogdan needs to update this issue please

**Comment by BogdanScherban** [comment]
I did following:
1) Custom list, with color border of News Score column;
2) Custom create/edit form (with color definition, popovers with rangeline and News score calculation);
3) Custom detail page;
4) Charts
5) Client side requests to the server side.

Only one issue should be solved:
https://github.com/PulseTile/PulseTile-RA/issues/92

**Comment by kuvakina** [comment]
**UPD from Bogdan** :
 There are two important changes:
1) Redirect to Patient summary page after 'Agree';
2) Vitals create and update with list refreshing

**From Phil** :
I've also noticed Vitals Popover functionality isn't in RA version, is this a conscious decision? Finally in the charts, in the previous version you could de-select categories/lines to make it clearer and when you selected an entry from the chart, the detail pane in the right would be shown

**From Bogdan** :
I added possibility to toggle lines at the Vital charts:
https://drive.google.com/file/d/1Rir6UFtud2ELy_JMHZ4k8Tjx_rkiH14u/view

 if we want to see popover, we should click on units (right on input field)

**From Phil** :
when selecting an entry from charts, it needs to appear in the right hand detail panel

when you select a summary row in the table view for any of the Tiles, it shows the detail in the right hand pane

so when in chart mode, that behaviour needs to be repeated. you select one of the dots in the chart, it takes you to the detail pane on the right hand side, for that entry

**From Bogdan** :
 I added this possibility:
https://drive.google.com/file/d/1BlmHlrZ6L8oDfhkESlHZTFX7Ur8w7u4x/view

**Comment by PhilBarrett** [comment]
@tony-shannon I think we can consider Vitals complete now, wdyt?

**Comment by PhilBarrett** [comment]
Hi @BogdanScherban 

We've noticed the ordering of vital signs isn't quite right (heart rate, Systolic, diastolic temperature)
Current view of RA showcase

![Screen Shot 2019-05-30 at 16.45.14.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/7e0f3b04-b577-4e73-a276-e2d8b6b39047)

Please can they be reordered so on the first row it appears
- Heart Rate
- Temperature

Second row
- Systolic
- Diastolic

**Comment by BogdanScherban** [comment]
@PhilBarrett 

OK, order was changed:
![Screenshot from 2019-05-31 13-13-41.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/ba17d49d-ebad-4b45-9313-e448b0d6562f)

**Comment by PhilBarrett** [comment]
Great thanks Bogdan, closing off this task.
