### ISSUE TITLE
Remove Tour from React-Admin showcase

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#21]

**Comment by kuvakina** [comment]
Tour was remover from React-Admin Showcase:
![ww3.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/f7f67c99-3048-404f-9021-07313145018a)
![ww2.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/9efb6593-49e7-49d0-95d0-289996904e8d)
![ww1.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/09e6a447-6a0f-4d4a-b698-399729680820)

**Comment by PhilBarrett** [comment]
Reviewed and closing, thanks
