### ISSUE TITLE
Heading not saving, editing or publish

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/Showcase-Project#25]
New headings for showcase-devra, we can't create them, edit or show them:
![Screenshot from 2019-05-23 12-15-58 (1).png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/87bb7b73-cd85-4abc-a192-08d4dc0d6b29)

**Comment by tony-shannon** [comment]
Dima has tested and working ok
Bogdan made some changes
Alexandra to retest

**Comment by kuvakina** [comment]
|   | Create | Edit | Comment |
| :---: | :---: | :---: | :---: |
| **Clinical Notes** | yes | yes   |  |
| **MDT** | yes | no | when edit, get the error from ethercis  |
| **Personal Notes** | yes | yes |    |
| **Procedures** | no | can't test |  In frontend missed field "time" , #26  |
| **Referrals** | yes | yes |    |
|  **Transfer Of Care** | no | can't test | problem discribed in #20   |
| **Vitals** | yes | yes, but Any Supplemental Oxygen automatically put On (even after edit) | Also one issue described in #19    |

**Comment by tony-shannon** [comment]
this one needs ongoing updates please @kuvakina , until completion

**Comment by PhilBarrett** [comment]
I've been doing some testing with Creates and working fine. 
@Kuvakina can we get an update please on edits

**Comment by kuvakina** [comment]
|   | Create | Edit | Comment |
| :---: | :---: | :---: | :---: |
| **Clinical Notes** | yes | yes   |  |
| **Clinical Notes** | yes | yes   |  |
| **Clinical Notes** | yes | yes   |  |

**Comment by kuvakina** [comment]
@tony-shannon  @PhilBarrett  Tested sc-devra 04.06,2019 and noticed next:

|   | Create | Edit | Comment |
| :---: | :---: | :---: | --- |
| **Problems / Issues** | no | can't test   | When create the issue and click Complete btn, see that it was created: https://www.screencast.com/t/o5y2vmE4abp , but after save and reload, not getting any error messages either, but nothing in the message showing the detail I've recorded. Also For the issue see empty array |
| **Medications** | no | can't test   | When create the issue and click Complete btn, see that it was created: https://www.screencast.com/t/eH246Sise . but after save and reload, not getting any error messages either, but nothing in the message showing the detail I've recorded. Also For the issue see empty array |
| **Vaccinations** | no | no  | Create: create the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear. Same for Edit |
| **Allergies** | no | can't test  | Same as for **Problems / Issues** & **Medications** |
| **Contacts** | no | no | Same as for **Vaccinations** |
| **Top Three Things** | no | can't test  | Same as for **Problems / Issues** & **Medications**  |
| **Clinical Notes** | no | no | Same as for **Vaccinations** |
| **Generic MDT** | no | no | Create: create the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear. Edit:  error: "#1.0.0 Invocation exception to method:update:java.lang.IllegalArgumentException: failed to create new instance of HIER_OBJECT_ID: IllegalArgumentException: wrong format, valueMap: {     value=java.lang.String:ethercis-204c7474-cbbe-4b34-b5cf-b07dcac711cd}" path: "/api/patients/:patientId/:heading/:sourceId" |
| **Personal Notes** | no | no | Same as for **Vaccinations** |
| **Procedures** | no | no | Same as for **Vaccinations** |
| **Referrals** | no | no | Same as for **Vaccinations** |
| **Transfers of Care** | no | no | Issue #20  |
| **Vitals** | no | no | Same as for **Vaccinations** |

**Comment by kuvakina** [comment]
@tony-shannon  @PhilBarrett  Dima noticed the issue with roles, and now I can create next issues:

|   | Create | Edit | Comment |
| :---: | :---: | :---: | --- |
| **Problems / Issues** | yes | no | When edit the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear |
| **Medications** | yes | no | When edit the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear |
| **Vaccinations** | yes | no | When edit the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear |
| **Allergies** | yes | no | When edit the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear |
| **Contacts** | yes | no | When edit the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear |
| **Top Three Things** | yes | no | When edit the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear  |
| **Clinical Notes** | yes | no | When edit the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear |
| **Generic MDT** | yes | no | Edit:  error: "#1.0.0 Invocation exception to method:update:java.lang.IllegalArgumentException: failed to create new instance of HIER_OBJECT_ID: IllegalArgumentException: wrong format, valueMap: {     value=java.lang.String:ethercis-204c7474-cbbe-4b34-b5cf-b07dcac711cd}" path: "/api/patients/:patientId/:heading/:sourceId" |
| **Personal Notes** | yes | no | When edit the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear |
| **Procedures** | yes | no | When edit the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear. When you edit second time, got: error: "#1.0.0 Invocation exception to method:update:java.lang.IllegalArgumentException: failed to create new instance of HIER_OBJECT_ID: IllegalArgumentException: wrong format, valueMap: {    value=java.lang.String:ethercis-bb22ee5e-02ca-4d14-851d-e2c586fa45a2}"     path: "/api/patients/:patientId/:heading/:sourceId" |
| **Referrals** | yes | no | When edit the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear |
| **Transfers of Care** | no | no | Issue #20  |
| **Vitals** | yes | no | When edit the issue, save it and see result. But when you go on another issue or reload page, your saved issue disappear |

**Comment by tony-shannon** [comment]
thanks for update @kuvakina 

@DmitrySolyannik to suggest next steps please

**Comment by PhilBarrett** [comment]
This is linked with RBAC issue which needs updating to create two roles (Patient and Doctor).

See #64 for details

**Comment by PhilBarrett** [comment]
@DmitrySolyannik can we get an update please

**Comment by kuvakina** [comment]
@PhilBarrett @tony-shannon I've testes showcase-devra on Create/Edit headings:

|   | Create | Edit | Comment |
| :--- | :---: | :---: | --- |
| **Problems / Issues** | yes | yes |  |
| **Medications** | yes | yes |  |
| **Vaccinations** | yes | yes |  |
| **Allergies** | yes | yes |  |
| **Contacts** | yes | yes |  |
| **Top Three Things** | yes | yes |  |
| **Clinical Notes** | yes | yes |  |
| **Generic MDT** | yes | no | Edit:  error: "#1.0.0 Invocation exception to method:update:java.lang.IllegalArgumentException: failed to create new instance of HIER_OBJECT_ID: IllegalArgumentException: wrong format, valueMap: {     value=java.lang.String:ethercis-9b7bf873-66c6-44fe-8a25-4d3bbbdb90a7}"    path: "/api/patients/:patientId/:heading/:sourceId" |
| **Events** | yes | yes | Just one moment: right now Events general for all patients |
| **Personal Notes** | yes | yes |  |
| **Procedures** | yes | yes |  |
| **Referrals** | yes | yes |  |
| **Transfers of Care** | no | no | Issue #20  |
| **Vitals** | yes | yes |  |
| **ReSPECT** | yes | yes |  |


@BogdanScherban will check MDT

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

We found an error in MDT edit action:

My request:
![Screenshot from 2019-07-16 14-41-06](https://user-images.githubusercontent.com/39263134/61291941-979e0180-a7d8-11e9-9065-ebc5d93b54c1.png)

Error description:
error: "#1.0.0 Invocation exception to method:update:java.lang.IllegalArgumentException: failed to create new instance of HIER_OBJECT_ID: IllegalArgumentException: wrong format, valueMap: {     value=java.lang.String:ethercis-5922a1c6-7475-495c-8377-3c68462feded}"

I checked format according to Documentation http://docs.pulsetile.com/react-mdt.html and assumed, that the reason is dateCreated format. I tried to change it:
![Screenshot from 2019-07-16 14-52-47](https://user-images.githubusercontent.com/39263134/61292357-adf88d00-a7d9-11e9-9bc0-c1a14a17e916.png)

But my result with Unix format for dateCreated was the same.

I asked @DmitrySolyannik about it. Dima assumed, that the reason isn't in QWED. The reason of error in Ethercis. 

Who can help us check the reason of error?

**Comment by freshehr** [comment]
Nope - you are picking up the wrong ID from QEWD - Rob has tried to explain this several times already. The sourceID has to be the original compositionID not the local QEWD cached identifier for the composition.

**Comment by kuvakina** [comment]
Thanks, Ian @freshehr

Problem with MDT described in this issue: https://github.com/QEWD-Courier/QEWD-Courier/issues/84

**Comment by tony-shannon** [comment]
ok as most all Headings working as planned except for known issues #20 Transfers of Care #84 MDT  so closing this for now
