### ISSUE TITLE
In frontend missed field "time" in Procedures

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/Showcase-Project#26]
In Showcase, in heading Procedures, QEWD waits for a " time " field from frontend. But there is no such field on Frontend. 
Should Bogdan add it to Frontend or  Dima has to remove/edit this field?

@BogdanScherban @DmitrySolyannik Could you please estimate the work on your side?

**Comment by kuvakina** [comment]
@PhilBarrett @tony-shannon 

Bogdan needs 2h  for this task (he found time field in documentation, but need to understand how to implement it)

Dima would need 1h (including to add tests), but we can't be sure, that EtherCIS will accept it

**Comment by BogdanScherban** [comment]
This issue should be solved by custom form creation. I'll do this, when I finish work on Patient List.

**Comment by BogdanScherban** [comment]
@tony-shannon 

This issue in process.

List - done, create - done.

Result on the video:
https://drive.google.com/file/d/1IhuJlZehvNCn7NQ4LNAtL7R8m0XdgOPR/view

Edit will be done next week, on Monday. I need 1-2 h for it.

**Comment by BogdanScherban** [comment]
This issue has been done:
https://drive.google.com/file/d/11hdaKnNY9_LU36cYtRxv1or4sZtqN9Tb/view

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett 
Bogdan added Procedures editing and updated it on Showcase:

as you can see we can create Procedures:
![sss5.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/b1d821be-b74d-4f20-b08f-8e06ce1f11ee)

But result not saved because EtherCIS not creating patient ID (the issue raised in QEWD chat)

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett We can save Procedures right now.

**Comment by PhilBarrett** [comment]
Thanks for the update @kuvakina. Procedures aren't saving correctly it would appear;

 - Procedure Performed By - reverts to 'performer' regardless of what is entered
 - I am unable to edit the date

Can you check your side please

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett @DmitrySolyannik 

I fixed this issue on the client side - time and data are saved. But look:
https://drive.google.com/file/d/1CAQmyNbabvNrQVgLc7REDKDAlfVfHt1W/view

Date and time are saved with difference to initial value.

**Comment by PhilBarrett** [comment]
Reviewed also and working fine, thank you.
