### ISSUE TITLE
Update FHIR MPI for Showcase

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/Showcase-Project#28]
We have to update FHIR MPI for Showcase.

**Comment by DmitrySolyannik** [comment]
@tony-shannon , @PhilBarrett
Uploaded FHIR MPI to showcase server. 
@kuvakina  could you please approve that everything works fine?

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett yes, it's working. Could we close this issue?

**Comment by PhilBarrett** [comment]
Reviewed and happy to close
