### ISSUE TITLE
MDT - LeftHandSide menu disappears

### ISSUE THREAD

**Issue by BogdanScherban** [PulseTile/Showcase-Project#3]
Left sidebar menu is hidden when user click on the row in Generator MDT list table.

**Comment by BogdanScherban** [comment]
This bug was fixed:
![mdt](https://user-images.githubusercontent.com/39263134/47222545-b7c2a080-d3bf-11e8-9942-f9e17052d3b7.png)

The reason was in MDT sidebar configurations
(name was "mdt" instead of "mdts")

**Comment by PhilBarrett** [comment]
Reviewed and resolved, thank you
