### ISSUE TITLE
Plugin Vitals: add functionality

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/Showcase-Project#32]
1) When goes request for Vitals list, the oxygenSupplemental parameter always return true

2) in the parameters list that returns after a request for Vitals list (GET) we have to add an index number

**Comment by BogdanScherban** [comment]
@tony-shannon @DmitrySolyannik 

This is my POST-request to create new Vitals:
![Screenshot from 2019-06-04 16-00-39](https://user-images.githubusercontent.com/39263134/58881223-69f67080-86e2-11e9-9ec3-6df1cf7a7796.png)

Creation was successful. And you can see that oxygenSupplemental was **false** in request-JSON.

But look at list of Vitals, which we get after this:
![Screenshot from 2019-06-04 16-02-09](https://user-images.githubusercontent.com/39263134/58881309-9ca06900-86e2-11e9-8cee-ade28ad3572b.png)

You can see that oxygenSupplemental is **true**.

**Comment by PhilBarrett** [comment]
@kuvakina providing update following checks

**Comment by BogdanScherban** [comment]
I checked - it works. I created new Vitals with Oxygen Supplemental - false:
![Screenshot from 2019-06-10 12-31-38.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/32c2cda6-469c-4117-9c24-0956c3288160)
![Screenshot from 2019-06-10 12-31-56.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/c17f05ba-6391-4171-8432-c999345b8d7f)

As result we can see false in details panel:
![Screenshot from 2019-06-10 12-34-20.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/223e8396-5670-4100-9ede-e7fa6f76b42e)
![Screenshot from 2019-06-10 12-34-34.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/8dd61db9-4b91-4ea8-91f3-9c1e0157e6ed)

**Comment by kuvakina** [comment]
Noticed that issue with radio buttons still present. Bogdan is looking into it.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

This issue has been done:
https://drive.google.com/file/d/1FfpXAAJBbCqLH3K8JjtepCA_VM-ae9he/view

**Comment by PhilBarrett** [comment]
@kuvakina Testing/reviewing and to update here

**Comment by PhilBarrett** [comment]
Reviewed and happy to close
