### ISSUE TITLE
High: Charts

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#35]
Suggest charts are move into their own panels

![Screen Shot 2019-05-30 at 14.55.46.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/89bf7af1-3efd-4acd-805c-b221aa7d9ab7)

See revised wireframes for context..

https://invis.io/KPS95C2ZR6X#/366179526_Charts

**Comment by BogdanScherban** [comment]
@simongamester 

Simon, do you suggest to locate two charts in two separate panels? 
Like in Showcase-reactJS?

**Comment by simongamester** [comment]
Yes please. Both use 50% of the screen space.

**Comment by BogdanScherban** [comment]
OK! I need in 1-1.5 h for this issue.

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett @simongamester 
Bogdan moved charts to their own panels:
![sss4.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/3afe7f17-2b2f-40b9-8b3c-3e9c700b752a)

**Comment by simongamester** [comment]
Thanks @BogdanScherban 

@PhilBarrett These look good to me.
