### ISSUE TITLE
Medium: Search submission on pressing ENTER

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#36]
Pressing the ENTER key should submit the search box in the top right. Currently, users must click the search button to submit a search query.

**Comment by BogdanScherban** [comment]
I need in 0.5-1 h for this issue.

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett @simongamester 

We can search by ENTER in Showcase-devra. Please check it

**Comment by PhilBarrett** [comment]
Reviewed, working fine, thank you.

@tony-shannon this was a gremlin on NES as well, one for handover and for them to draw down?
