### ISSUE TITLE
High: Search button placement

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#37]
Recommend removing the space between the search text box and the button(s) to the right. This can be achieved be setting the margin-right on the text box to “0”:

![Screen Shot 2019-05-30 at 15.05.38.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/07846d21-dd9a-4b18-bf3b-d5b95c5bd3ec)

**Comment by BogdanScherban** [comment]
thanks @simongamester 
@tony-shannon  @PhilBarrett for this task I need 15 minutes

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett @simongamester 
the spaces in search were removed:
![sss1.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/9802912a-16a7-44e4-8faf-9244a88ad574)
![sss.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/2b74681f-19ec-436c-85ae-52f4cadad720)

**Comment by simongamester** [comment]
@PhilBarrett This looks to be resolved.
