### ISSUE TITLE
High: Rounded Buttons

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#38]
Apply rounded edges to all buttons. Border-radius: 25px should be enough for most large buttons however smaller ones may need to be less.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

As I understand, we supposed to change UI of showcase-devra to be identical to old Showcase-ReactJS (with rectangular buttons instead of rounded) and it has been done.

Should we change UI back to rounded buttons? 

If we have to do this, I need in 0.5h.

**Comment by PhilBarrett** [comment]
Yes please

**Comment by PhilBarrett** [comment]
Confirmed by Bogdan as being completed and ready for review.

**Comment by simongamester** [comment]
@PhilBarrett Looks good to me!
