### ISSUE TITLE
Low: Buttons within rows

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#39]
Buttons within rows as shown within the should appear the same whether the user is highlighting the row or not i.e. green border, white background, green text. Currently, buttons adopt a green background and white text when the row is hovered, see below:
![Screen Shot 2019-05-30 at 15.08.11.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/102a5375-013b-4b59-8614-9f8970c85d07)

**Comment by BogdanScherban** [comment]
@simongamester 

Simon, as I understand you correctly:
1) When user hover on row - button should be white with green text;
2) When user hover on the button - the same? Without hover effect by changing the color?

**Comment by simongamester** [comment]
1. Yes
2. That's a good point. For now, I think we should disable hover effects on these. So just leave them white background with green text as in point 1.

**Comment by BogdanScherban** [comment]
OK! I need in 0.25-0.5 h for this issue

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett @simongamester 

Bogdan made this:
![sss10.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/a9af6f85-020c-4456-8bcb-608a29de0445)

**Comment by simongamester** [comment]
@BogdanScherban I made a comment on this in another issue:

https://github.com/RippleOSI/Ripple-Showcase-Stack-Project/issues/41#issuecomment-498344290

Buttons now don't display correctly when not hovering.

**Comment by BogdanScherban** [comment]
@simongamester 

The issue has been done:
https://drive.google.com/file/d/1x_aXd87z8rbn3J0IwmLCLv4iCmEnrA0C/view

**Comment by simongamester** [comment]
@PhilBarrett This has been done.
