### ISSUE TITLE
Medium: Panel Spacing and Shadows

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#40]
Dashboard widgets should be spaced slightly further apart and shadows should be applied to the outer panel’s div element. 

Would recommend increasing the padding of the outer element from 8px to 15px as shown:
![Screen Shot 2019-05-30 at 15.09.43.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/d2334fe7-3024-4089-b245-271ac8dd3e71)

Apply a box shadow to the panels I think the following would be about right:

![Screen Shot 2019-05-30 at 15.10.07.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/2fd221e6-6bc0-4ed5-b5f0-01623418d026)

**Comment by BogdanScherban** [comment]
@simongamester 

Simon, could you please provide us with screenshots of panels, where we have to add it.

**Comment by simongamester** [comment]
@BogdanScherban Here's an example of a panel and the DIV we'd like to apply spacing:

![Screenshot 2019-05-31 at 10 31 10](https://user-images.githubusercontent.com/8059219/58696490-94b59180-838f-11e9-8bf0-62522b7eff99.png)

Here's the inner DIV where we'd like to apply shadows.

![Screenshot 2019-05-31 at 10 30 58](https://user-images.githubusercontent.com/8059219/58696360-54561380-838f-11e9-8fef-08d4421b70b1.png)

I'm assuming all 'panels' use the same styles, however anything with a green header and white box should adopt the same shadow styling, so this would also include panels containing tables views or records and forms.

**Comment by BogdanScherban** [comment]
@simongamester 

Simon, should it be done ONLY for Showcase?
Or for all other projects (Helm, London, Nes) too.

In any case this issue need 0.25-0.5 h

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett @simongamester 

Bogdan added Panel Spacing and Shadows:
![sss6.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/63530224-c93a-4577-9125-02dead657dd2)

**Comment by simongamester** [comment]
@BogdanScherban The DIV containing panels also appears to now have a border, see screen...

![Screenshot 2019-06-03 at 18 03 01](https://user-images.githubusercontent.com/8059219/58820198-d6f9ff80-8629-11e9-8bef-fb3691314db1.png)

This means that a line now appears below panels.

Here's the div which I think has the padding applied.

![Screenshot 2019-06-03 at 18 02 14](https://user-images.githubusercontent.com/8059219/58820230-f09b4700-8629-11e9-8440-b110b89dc223.png)

Also, the shadows should be applied to ALL panels through the system. This should not just include widgets as shown above but also panels containg table lists and and record information.

**Comment by simongamester** [comment]
@BogdanScherban I've just spotted another issue with the panels, which may be related to this Issue: The Create panels for Procedures, Transfers of Care, and Vitals appear to have no white background and no borders, see below...

![Screenshot 2019-06-04 at 09.54.38.png](https://images.zenhubusercontent.com/5cc737542781b443a5657ce1/906e344d-3fb0-4b44-8dbf-55d8faf60cdb)

![Screenshot 2019-06-04 at 09.54.49.png](https://images.zenhubusercontent.com/5cc737542781b443a5657ce1/bc586c85-5f71-438f-9bd9-a1575dc7489e)

![Screenshot 2019-06-04 at 09.54.43.png](https://images.zenhubusercontent.com/5cc737542781b443a5657ce1/b21ed0bf-fea6-403e-a1eb-724d2bcbbbb3)

**Comment by BogdanScherban** [comment]
@simongamester 

This issue has been done:
https://drive.google.com/file/d/1TCDSq7fWhUXWlM-2mgNo7Jl3MZVjFhEb/view

**Comment by simongamester** [comment]
@BogdanScherban I can see you've added the white backgrounds, however the borders are still missing.

**Comment by BogdanScherban** [comment]
@simongamester 

Sorry, Simon. Probably, I sent old video. Look:

![Screenshot from 2019-06-05 12-46-39.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/989cb420-9c2b-475b-8372-c997a198fceb)
![Screenshot from 2019-06-05 12-46-49.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/1924d437-ca20-4a69-bd7d-6af00f1c3d9e)
![Screenshot from 2019-06-05 12-46-59.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/ecfd08cd-433e-48db-959b-bbb75a90a42e)

![Screenshot from 2019-06-05 12-47-09.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/585445ab-ce32-4e11-a242-887663bc7936)
![Screenshot from 2019-06-05 12-47-16.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/024cd96c-80f6-49f7-8f29-fcb1c1e8c11a)
![Screenshot from 2019-06-05 12-47-25.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/876cf36f-0522-4681-891f-46b7a61ae564)

**Comment by simongamester** [comment]
Thanks @BogdanScherban, looks good.

@PhilBarrett ok to mark as resolved.
