### ISSUE TITLE
High: Panel header and table spacing

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#42]
There should be no gaps between the header of a panel and any tables that immediately follow:

![Screen Shot 2019-05-30 at 15.13.40.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/aaf3e28e-7d32-49f1-9414-2219e601f1f6)

In the example above, there should be no margin between the grey and light green row elements.

**Comment by BogdanScherban** [comment]
@simongamester 

Simon, could you please clarify this issue.

Old Showcase-ReactJS has gaps between header and table block, like this:
https://showcase-devra.ripple.foundation/#/patients

Should we do this gaps, if we create Showcase-RA UI identical to Showcase-ReactJS?

If it is necessary to remove it, I need in 0.25 h.

**Comment by simongamester** [comment]
Hi @BogdanScherban 

Yes, please remove as this gap wasn't present in our original InVision wireframes.

**Comment by kuvakina** [comment]
@simongamester 

> Yes, please remove as this gap wasn't present in our original InVision wireframes.

Sorry, Simon, we didn't know about InVision wireframes, we were working to do it identical to Showcase-react

**Comment by BogdanScherban** [comment]
OK, I need in 0.2-0,25 h for this.

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett @simongamester 

the spaces in tables were removed:
![sss2.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/e308762b-cba1-494a-a7d4-5312f9507b52)
![sss3.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/1fa93410-6c0c-419a-bc32-969409a3c673)

**Comment by simongamester** [comment]
@BogdanScherban This looks correct within the tables, however it looks like the top and bottom padding around the information (right) panels are now too close to the edges.

![Screenshot 2019-06-03 at 17 57 53](https://user-images.githubusercontent.com/8059219/58819962-3f94ac80-8629-11e9-94fc-620659ed2c38.png)

(See the label for 'Problem Issue'.

Also the Edit button is too close to the 'System Information' header below it.

**Comment by BogdanScherban** [comment]
@simongamester 

OK, so should I added:
1) padding bottom to Edit button?
2) padding right to Edit/Create/Details block?

**Comment by simongamester** [comment]
I would suggest adding top and bottom padding to this element:

![Screenshot 2019-06-04 at 14.04.16.png](https://images.zenhubusercontent.com/5cc737542781b443a5657ce1/063aa139-ce81-40a5-9ba0-60812d0296c0)

Maybe padding: 10px 0;

**Comment by BogdanScherban** [comment]
@simongamester 

This issue has been done:
![Screenshot from 2019-06-05 11-30-34.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/e117144b-8bdf-4fd2-a78b-c36dad1288e3)

**Comment by simongamester** [comment]
I think it's actually the div above this one that we need to apply padding to. The one you added the padding to doesn't include the edit button, which is still close to the edge. I've applied in my browser to give an example of how is should look...

![Screenshot 2019-06-05 at 09 42 39](https://user-images.githubusercontent.com/8059219/58942836-6f04ff80-8776-11e9-884d-2120f12f81a8.png)

**Comment by BogdanScherban** [comment]
@simongamester 

Simon, I added borders:
https://drive.google.com/file/d/1s73upT7PzSUyGa7-Iqyj9_s7PeArfUno/view

**Comment by simongamester** [comment]
Thanks @BogdanScherban much better :-)

@PhilBarrett can you mark as resolved please.
