### ISSUE TITLE
High: Icons in Buttons

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#44]
The placement of icons within buttons requires minor adjustments, see example below:

![Screen Shot 2019-05-30 at 15.16.26.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/7461bf8b-3407-495b-b36a-1ba48412b68d)

In all cases, icons should be moved about 5px away from the text. In addition, the tick for the ‘Complete’ button does now appear to be aligned correctly. Suggest moving this down about 5px.

**Comment by BogdanScherban** [comment]
@simongamester 

Thanks, I understand. I need 0.5 h for this issue.

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett @simongamester 

Bogdan fixed this:
![sss7.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/a5f229d2-b512-4aef-8a80-9614a4550ed6)
![sss8.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/f39a5ee8-9f3a-4e97-a5fd-6e7b904d20ee)

**Comment by simongamester** [comment]
@BogdanScherban @PhilBarrett Looks good to me :-)
