### ISSUE TITLE
Medium: Patient Summary Padding

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#45]
The text within the patient summary appears to be too close to the edges of the box:
![Screen Shot 2019-05-30 at 15.17.27.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/29b6260a-a478-4958-8931-1f960b6af63d)

For some reason, the padding that places the text within the green box is applied to each block of text, not the outer element of the summary

![Screen Shot 2019-05-30 at 15.18.13.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/688111d0-408e-4e5c-909a-e53001de94d7)

I would suggest this is remove altogether and 10px padding is applied to the outer element instead:

![Screen Shot 2019-05-30 at 15.18.20.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/b86b782c-3b15-4243-b551-0277c28d153d)

**Comment by BogdanScherban** [comment]
OK, this task would require approx 0.25-0.5 h

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett @simongamester 
Bogdan applied changes to Patient Summary Padding:
![sss9.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/7e809df4-c0d3-4741-bc9d-2571045509ab)

**Comment by simongamester** [comment]
@BogdanScherban @PhilBarrett Yes, this looks good.
