### ISSUE TITLE
Low: Patient Summary Address

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#46]
It looks like the address is in a different DIV to the patient name, but I’m not sure why this is. 

In some cases the patient’s doctor is displayed immediately below the name, however when this is blank, it creates a large space which increases the height of the patient summary unnescessarily. 

![Screen Shot 2019-05-30 at 15.20.14.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/246edb7f-47d1-49d7-a493-dd44e9cf1df7)
I would suggest moving the address to immediately follow the patient’s doctor on a new line.

![Screen Shot 2019-05-30 at 15.20.19.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/84d2b687-7fb5-43f5-9e17-e69e134b7324)

**Comment by BogdanScherban** [comment]
@simongamester 

Address line was located in the separate div below, to give possibility to locate doctor info below the patient name. 

Or you suggest to locate patient name, doctor and address in one div (vertical direction)?

**Comment by simongamester** [comment]
That's correct. All 3 fields would be within the same div. If doctor is not provided however, the address would automatically fall directly underneath the patient name.

**Comment by BogdanScherban** [comment]
OK, I need in 0.5 h for this issue.

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett @simongamester 

Bogdan changed it:
![sss11.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/dbbd1c5a-1506-4cb5-9231-5582f5ee5566)

**Comment by simongamester** [comment]
@PhilBarrett Do we have an example of a patient with a doctor? Would be worth testing this before signing this off.

**Comment by PhilBarrett** [comment]
@tony-shannon if it's been taken from NES work, I don't believe Doctor is in the address, so would need adding in to check

**Comment by kuvakina** [comment]
Sorry, @PhilBarrett @simongamester could we consider this task as done?

**Comment by simongamester** [comment]
Could @BogdanScherban send a screen with the Doctor field populated please? We have no way of confirming this field is being displayed correctly as none of the users in the showcase system have the Doctor field. A screenshot taken from dev would suffice.

**Comment by BogdanScherban** [comment]
@simongamester 

Simon, doctor field was presented in the old Showcase (with ReactJS). It was possible, because server side returned infor about doctor:
![Screenshot from 2019-06-05 11-39-06.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/9702b97c-e618-45ee-90e1-9170bd844e23)

But in Showcase-RA we use other request for user information, and doctor's info is absent here generally:
![Screenshot from 2019-06-05 11-39-34.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/300cdb39-af52-4eb9-83cb-042381bb57a6)

For this reason I can't display info about doctor.

But I changed structure of this block according to your suggestion:
https://github.com/PulseTile/PulseTile-RA/blob/b8f13b912114f1aa50b67e45aab776827ddf7940/src/core/common/Topbar/fragments/PatientBanner.js#L26

**Comment by simongamester** [comment]
Thanks @BogdanScherban 

For the purposes of testing, I'd like to see this field displayed on the screen, so could you tweak your local copy temporarily so the doctor code block is called?

If you add a line below here, for example:

https://github.com/PulseTile/PulseTile-RA/blob/b8f13b912114f1aa50b67e45aab776827ddf7940/src/core/common/Topbar/fragments/PatientBanner.js#L23

Which manually overrides the 'doctor' variable so calls the doctor to be displayed:

Something like:
`doctor = 'Daniels Yvonne C.';`

Then run the code, take a screenshot and remove the changes.

**Comment by BogdanScherban** [comment]
@simongamester 
OK, I added doctor (for test)

![Screenshot from 2019-06-05 13-36-54.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/318de507-ff35-4a0c-b00b-6ebdccc3c339)

**Comment by simongamester** [comment]
Thanks @BogdanScherban that looks fine to me.

@PhilBarrett this is done.
