### ISSUE TITLE
Medium: Cog hovering

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#47]
Hovering over the Cog on the dashboard reveals a grey circle behind which is not placed correctly over the cog.

![Screen Shot 2019-05-30 at 15.22.03.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/e3474178-1f46-4da4-935a-c07a3607113a)

In addition, the ‘Home’ wording is also clickable. Only the cog should be clickable.

**Comment by BogdanScherban** [comment]
OK, I need 0.5  for this task.

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett @simongamester 
This one was fixed:
![sss0.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/d01a976f-4f21-46e2-91bb-086dd64d0c9a)

**Comment by simongamester** [comment]
Thanks @BogdanScherban 

@PhilBarrett Ok with me.
