### ISSUE TITLE
Vital Signs - Popover change to hover

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#49]
Change Vital Signs popover from being viable when clicked, to viewable when hovered over

![Screen Shot 2019-05-30 at 15.26.17.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/a5667679-317e-4b34-9b1f-08a80e70267c)

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett 
Bogdan made Vital Signs popover  viewable when hovered over:
https://drive.google.com/file/d/12mZdAu2g86Y75PueWxJB-4ra24F1yZ45/view

**Comment by tony-shannon** [comment]
Very good , thanks

**Comment by PhilBarrett** [comment]
I've reviewed and can't see the popover for Diastolic BP. could this be added please @BogdanScherban

**Comment by BogdanScherban** [comment]
@PhilBarrett 
Yes, I can add popover for Diastolic BP, but which range values should I use?

In old Showcase-ReactJS this info is absent:
http://dev.ripple.foundation/#/patients/9999999061/vitals/create

**Comment by PhilBarrett** [comment]
![image_2019_06_05T16_15_23_092Z](https://user-images.githubusercontent.com/12699244/59018690-5eb85780-883e-11e9-84cf-cd6c0cc0618c.png)
@BogdanScherban please use these ranges for Diastolic

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

I have a Q about values in this table. Please, look at the rangeline for Systolic pressure in Showcase-ReactJS:
![Screenshot from 2019-06-06 18-13-50.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/edcee9b7-92e0-47f1-a91b-01249cc7f41e)

1) You can see, that it has two limits - left and right. At the table upper we can see only right limit (from green-120 till red-180)
2) Values in rangeline on the screenshot aren't correspond to the table upper. According to old Showcase-RJ:

right green border - near 111
right red border - more than 220
So, could you please clarify values for rangeline.

**Comment by tony-shannon** [comment]
![image.png](https://images.zenhubusercontent.com/5c8be461fd0adb6f09c83d64/f4bf035e-d156-4978-9076-49bd8164e882)

Going to park /close this issue for now as DBP not in NEWS scor

**Comment by PhilBarrett** [comment]
@BogdanScherban please can you remove the logic that sets the background to green/amber/red
![Screen Shot 2019-06-10 at 12 07 59](https://user-images.githubusercontent.com/12699244/59191838-824e0b80-8b78-11e9-911d-c8ec94fe0e8c.png)

Also remove the popover for diastolic

![Screen Shot 2019-06-10 at 12 07 46](https://user-images.githubusercontent.com/12699244/59191866-9bef5300-8b78-11e9-857a-35bd2efd589c.png)

**Comment by BogdanScherban** [comment]
@PhilBarrett 
Only for diastolicBP? Or for all other values?

**Comment by BogdanScherban** [comment]
OK, I've removed this logic from diastolicBP.

**Comment by PhilBarrett** [comment]
Closing issue. thanks Bogdan
