### ISSUE TITLE
Replace Icons at SPV headings

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#52]
Currently like this

![Screen Shot 2019-05-30 at 15.36.13.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/7d3d9aac-dc04-4551-94f5-dc78252577ba)

Needs to go back to this as per React showcase

![Screen Shot 2019-05-30 at 15.35.19.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/444216c2-b137-4ce5-bec8-7d41f9aa4ddb)

**Comment by BogdanScherban** [comment]
@PhilBarrett @tony-shannon 
This issue has been done:
![Screenshot from 2019-06-05 13-41-45](https://user-images.githubusercontent.com/39263134/58950525-af28aa00-8797-11e9-9fb6-44447f9b321c.png)

**Comment by PhilBarrett** [comment]
@simongamester are there icons we can use in the React-admin version (thinking font awesome) that replicate the filter and expand icons from the old showcase 

React-Admin showcase that needs to change 
![Screen Shot 2019-06-06 at 11.19.53.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/3e67dcc4-d2fe-4fd2-9bdf-2578f3982e1e)

to react.js showcase 
![Screen Shot 2019-06-06 at 11.19.45.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/c993f157-3e33-466a-9efa-2a4022795a43)

**Comment by BogdanScherban** [comment]
@simongamester @PhilBarrett 

We used icons from these free library:
https://material.io/tools/icons/?icon=3d_rotation&style=baseline
https://fontawesome.com/icons?d=gallery

But we didn't find required free icons, and used presented.

**Comment by simongamester** [comment]
@PhilBarrett Yes, assuming the react-admin version uses FontAwesome 5, you could use the following:

To expand full screen:
https://fontawesome.com/icons/expand-alt?style=solid

Then to collapse full screen:
https://fontawesome.com/icons/compress-alt?style=solid

Filter icon can be found here:
https://fontawesome.com/icons/filter?style=solid

I'm not sure how Bogdan has coded the icon into the UI, but you can either do this with html e.g. 

<i class="fas fa-filter"></i>

or by applying css to the element:

``div:before {``
``  font-family: 'FontAwesome';``
``  content: '\f0b0';``
``}``

**Comment by simongamester** [comment]
Maybe you're using version 4?

Expand in v4
https://fontawesome.com/v4.7.0/icon/expand

Collapse in v4
https://fontawesome.com/v4.7.0/icon/compress

Filter:
https://fontawesome.com/v4.7.0/icon/filter

**Comment by BogdanScherban** [comment]
@PhilBarrett @tony-shannon 

The issue has been done:
![Screenshot from 2019-06-10 17-20-09.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/8f2529d7-60de-4256-aa6a-06c0f89460eb)

**Comment by PhilBarrett** [comment]
Reviewed and working fine.
