### ISSUE TITLE
Showcase cosmetic enhancements

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#58]

**Comment by PhilBarrett** [comment]
Hi @kuvakina, following Simon's review of the RA showcase,  I've grouped the changes together for ease. Please could we get estimates on each of the subtasks and we'll then make a call on which to proceed with.  

Thank you :)

**Comment by kuvakina** [comment]
thanks @PhilBarrett and  @simongamester 

Tomorrow we prepare estimates for the tasks

**Comment by PhilBarrett** [comment]
Sub tasks completed, closing this Epic
