### ISSUE TITLE
Results for checkbox in cog menu not saved on frontend

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/Showcase-Project#60]
The issue in the video: https://drive.google.com/file/d/1yGBWBNrEEimobYiRt1DHFcno5tq7t82z/view

When we chose to Select all or Deselect, results are saved and applying even for a new search. But on the front part, it reversed to default (in cog menu). And that's why we see like its working incorrect.

**Comment by BogdanScherban** [comment]
This issue is related with this one:
https://app.zenhub.com/workspaces/ripple-combined-project-space-5c8be494fd0adb6f09c83d6b/issues/rippleosi/ripple-showcase-stack-project/61

The reason of errors is common.

I need in 2-4 h for both these issues.

**Comment by kuvakina** [comment]
This issue is done, @tony-shannon @PhilBarrett ,  you can see in the video: https://drive.google.com/file/d/10eEvmd84qbOVLfCfpG2Sui9QgsqazjXe/view

**Comment by PhilBarrett** [comment]
Reviewed as well, working great, thank you
