### ISSUE TITLE
Have a bug after second search for patient

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/Showcase-Project#61]
There is a bug: https://drive.google.com/file/d/1s4R9d53tU9EgFg86wDlOS7tCSo0gqb--/view

Bogdan says that for some reason when you click to search the second time, columns from cog menu are opens.

**Comment by BogdanScherban** [comment]
This issue is related with this one:
https://app.zenhub.com/workspaces/ripple-combined-project-space-5c8be494fd0adb6f09c83d6b/issues/rippleosi/ripple-showcase-stack-project/60

The reason of errors is common.

I need in 2-4 h for both these issues.

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett 

Tested, the issue doesn't appear anymore.

**Comment by PhilBarrett** [comment]
> @tony-shannon @PhilBarrett
> 
> Tested, the issue doesn't appear anymore.

Same, closing as resolved
