### ISSUE TITLE
Add an extra Role in OIDC for Showcase Stack 

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/Showcase-Project#64]
Need to get both PHR and IDCR roles working again with our showcase stack , so need to revisit this in authentication service

**Comment by tony-shannon** [comment]
Need estimate of effort from @Robtweed to reinstate at least  2 roles (PHR & IDCR) & related RBAC in the stack via either;
- hard code another role into Qewd-Courier 
- add another role to OIDC 
- and/or switch to Auth0

need discussion with @DmitrySolyannik 

NB See here for user/role logic from earlier version
https://github.com/RippleOSI/Ripple-Qewd/blob/master/lib/user/user.js

**Comment by tony-shannon** [comment]
updated discussion with RT on this

_Yes - if he wants to start work on it, all he needs to do is set/change the role property/claim in the JWT to either IDCR or PHR (or whatever values you want to use for these roles), and modify the application logic in QEWD Courier appropriately - he don't need to wait till the role is coming back from the OIDC provider_

_it's just a property in the JWT that he can change anywhere and any time in his logic_

_All I'll be doing is returning the role as a property in the idToken returned by the OIDC Provider when they log in via the OIDC Provider_

_So Dima can hack his code to simulate what will be eventually set up in the JWT_

**Comment by tony-shannon** [comment]
@DmitrySolyannik can you consider an interim hack to add behaviour
eg

if user email == ivor.cox@gmail.com
then userrole = PHR and NHS# = 9999990000
else userrole = IDCR

**Comment by PhilBarrett** [comment]
Awaiting PR from @DmitrySolyannik

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett 

Dima created the user and PR for Ivor Cox. 

@BogdanScherban could you please add restrictions for this user?

**Comment by PhilBarrett** [comment]
Reviewed and working fine
