### ISSUE TITLE
Global change for pagination

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#69]
When creating new entry for any of the headings or patient it doesn’t appear, I have to either refresh or click on pagination arrow and then go back to see the result.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

I need in 1-2 h for this issue.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

This issue has been done:
https://drive.google.com/file/d/1zM3vz2Tz0ol5DWQo3UPeVQIZP6hmtlWZ/view

**Comment by PhilBarrett** [comment]
Reviewed and closing, thank you
