### ISSUE TITLE
Can open Diagnose datails without Diagnoses

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/Showcase-Project#7]
We can open diagnose details when we have no diagnoses at all: https://www.screencast.com/t/qQv1l2nM1

Related issue #268 https://waffle.io/RippleOSI/combined-development-view/cards/5bcdcb84f4c0a7004421f3b8

**Comment by tony-shannon** [comment]
ok thanks @kuvakina 
Think we can live with that for now, but ideas on how to resolve are welcome

@PhilBarrett any other view?

**Comment by kuvakina** [comment]
Thank you, @tony-shannon 

We'll try to look into it

**Comment by kuvakina** [comment]
Raised in Helm: https://waffle.io/RippleOSI/combined-development-view/cards/5bcdf01f2c62d200576fd2fe
