### ISSUE TITLE
Remove T&C upon login for Showcase

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#70]
No longer required.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

I need in 10 min for this issue, but only Dima can upload user login part. I'll prepare changes and ask him to upload it.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

This issue has been done

**Comment by kuvakina** [comment]
@PhilBarrett @tony-shannon 

You can see result in the video: https://drive.google.com/file/d/1PvUn6KeOd2WV5bjM0gnv4FNxaJascpT9/view

**Comment by PhilBarrett** [comment]
Confirmed as removed.
