### ISSUE TITLE
Font typeface inconsistencies

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#71]
Please can there be a brief review of showcase as I can see typeface/size inconsistencies with data entry and the initial loading messages when you log in for example

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

Could you please clarify, where we should change font typeface? Screenshots would be very helpful.

**Comment by PhilBarrett** [comment]
@kuvakina I'd like this to be covered as part of the review process. I've included two examples already

**Comment by PhilBarrett** [comment]
This is for both the Loading spinner and for charts

**Comment by kuvakina** [comment]
>This is for both the Loading spinner and for charts

@BogdanScherban please fix this one

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

This issue has been done:
https://drive.google.com/file/d/16RdUVkfWM0pAvHZwe7WAucP2x33htzhK/view

**Comment by PhilBarrett** [comment]
Work completed - https://drive.google.com/file/d/16RdUVkfWM0pAvHZwe7WAucP2x33htzhK/view

**Comment by PhilBarrett** [comment]
Reviewed and closing
