### ISSUE TITLE
MPV - unable to drill down into the record from counts or date/time into that detail

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#72]
In the old showcase (react) we had the ability to click on either counts or dates for any of the headings in the multipatient view (patient lists) and be taken to that heading list view for the patient.

In react-admin this function isn't available and would be helpful.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

Do you mean that when we click on any cell in a row modal window should appear?

On Nes and OneLondon we can see patient details. We don't need it in Showcase?

**Comment by PhilBarrett** [comment]
> @tony-shannon @PhilBarrett
> 
> Do you mean that when we click on any cell in a row modal window should appear?
> 
> On Nes and OneLondon we can see patient details. We don't need it in Showcase?

Ignoring the fact that counts aren't displaying in react version, please see video for what actually happens.

![MPV](https://user-images.githubusercontent.com/12699244/59282827-6f633600-8c61-11e9-8f46-aa432ef67a94.gif)

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

This issue has been done:
https://drive.google.com/file/d/1v806DUDSkRQjDfIyVvEb8t4DVZQ0ppei/view

**Comment by PhilBarrett** [comment]
This must not have been uploaded as I still encounter the same issue.

**Comment by BogdanScherban** [comment]
@PhilBarrett 

Click on Vitals or Problems redirects to SPV, but click on Results and Orders can't do this. Because we don't have this pages.

**Comment by PhilBarrett** [comment]
Agreed to remove Results / Orders

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

This issue has been done:
![Screenshot from 2019-06-18 16-53-20.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/814c0948-fc4d-4617-96f6-92baa4ff8050)

**Comment by kuvakina** [comment]
related to #31

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett 

Bogdan made it so now by clicking on Vitals or Problems we are forwarded to the issue:
https://drive.google.com/file/d/1yL0u4ACxNMStw4mm5oY3ZGeOezgy8Ol-/view

Can we consider this task as done?

**Comment by PhilBarrett** [comment]
Thanks @kuvakina
