### ISSUE TITLE
SPV - Patient summary screen

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#73]
- [x] Changes to settings cog, removing Feeds
 - [ ] Adding "headings + List" for ReSPECT so it's consistent with other tiles on the patient summary

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

> Changes to settings cog, removing Feeds

Do you mean to remove only Feeds from here?
![Screenshot from 2019-06-11 17-52-13.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/e216a378-d828-4e84-be9e-aae6184ef351)

>  Adding "headings + List" for ReSPECT so it's consistent with other tiles on the patient summary

Do you mean to add four latest versions to Respect panel?
Should Respect be also added to settings cog?

**Comment by PhilBarrett** [comment]
None of the feeds are working, nor are they added to the patient summary screen. If it's easy to get working again, for say NYtimes, Public Health and Medical news today, then please do, removing other options. Or three non city based feeds. 

Please add ReSPECT to the cog and Respect last 4 entries, so it all is uniform.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

This issue has been done:
![Screenshot from 2019-06-14 15-18-12.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/66174e00-733e-4505-a7c7-5d0cb97aed65)
![Screenshot from 2019-06-14 15-18-51.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/909803f4-93bf-4f15-9fcb-67afc01c2ffe)
