### ISSUE TITLE
Vitals - aren’t numbered in list view

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#74]
![Screen Shot 2019-06-11 at 11.26.14.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/348467e4-a8df-4483-999d-b7aa7d24a768)

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett

For this task, Bogdan needs 2-3 hours

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

This issue has been done:
![Screenshot from 2019-06-14 15-17-32.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/156fc93e-8365-4344-aff5-a7a8c0e880c2)

**Comment by PhilBarrett** [comment]
Reviewed and closing, thanks
