### ISSUE TITLE
Top3Things. Complete button not working

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/Showcase-Project#8]
When a user wants to add Top3Thing:
1) they go to Top Three Things
2) they click Create button and see Create Top Three Things details on the right
3) they add 1-3 Top3Things and click Complete button

Should be: 1-3 changes to Top3Things have to be saved and shown in table

Bug: nothing happens when a user clicks Complete button: https://www.screencast.com/t/aMFkQf7eiXJJ

Assume that problem is in server response:
https://www.screencast.com/t/OXaIpC7u3nA

**Comment by BogdanScherban** [comment]
@kuvakina

Alexandra, could you please add screenshots with Network/Headers tab?
It is necessary to see text of request to server.

**Comment by tony-shannon** [comment]
yes, this needs more detail on server request/response please

**Comment by kuvakina** [comment]
yes, see below, please:

https://www.screencast.com/t/2TLfpwrP6w

**Comment by kuvakina** [comment]
Raised in Helm: https://waffle.io/RippleOSI/combined-development-view/cards/5bcdefd9ab14ba00b1c05739
