### ISSUE TITLE
Remove start time from Medications

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#81]
No longer required

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

I need in 0.5 h for this issue.

**Comment by kuvakina** [comment]
@DmitrySolyannik could you please check templates to see if we can remove start time from Medications

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

This issue has been done:
![Screenshot from 2019-06-18 17-48-31.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/d9be3824-e589-4821-bf0f-91a35bbe8698)

**Comment by PhilBarrett** [comment]
Reviewed and happy to close, thanks
