### ISSUE TITLE
Test Results Module

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#84]
We're looking to reproduce the test results module from the react.js variant but in React-Admin

http://docs.pulsetile.com/react-test-results.html

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

This issue has been done:
https://drive.google.com/file/d/1JAGs85KpAf5XnMwhrz6mmUp2GXwnuUnU/view

**Comment by PhilBarrett** [comment]
Reviewed and happy to close
