### ISSUE TITLE
Showcase Bugs/tidyup 24/6/19

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#85]
- [ ]  Counts 
 - [x] Address issue
 - [x] Responsive issues (MPV)
- [x]  Profile picture
- [x] Empty/dummy result
- [x] Line between Problems/medications/allergies not clear enough
- [x] Discuss timeline events
- [x] Copyright notice states 2018, needs updating please
 - [x] - Please can you add these two further hardcoded entries underneath Height:
CPR Status For active CPR
Blood Group O+
Donor status Organ Donor

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 
Done:
- Address issue
- Empty/dummy result
- Line between Problems/medications/allergies not clear enough
- Copyright notice states 2018, needs updating please
- Please can you add these two further hardcoded entries underneath Height:
CPR Status For active CPR
Blood Group O+
Donor status Organ Donor

**Comment by BogdanScherban** [comment]
Responsive problem has been solved.

**Comment by kuvakina** [comment]
@BogdanScherban are these also solved?

- [ ] Counts
- [ ] Responsive issues (MPV)

**Comment by BogdanScherban** [comment]
@kuvakina 
Responsive issues (MPV) - done.
Count - what should I do? Remove count-requests? Or remove count columns?

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett 

what should Bogdan do with Counts:
>Count - what should I do? Remove count-requests? Or remove count columns?

**Comment by PhilBarrett** [comment]
We'll keep counts functioning with dummy counts data for now. 

Closing
