### ISSUE TITLE
Documentation for related PulseTile Generator & End2End tests

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/Showcase-Project#9]
Need the repos for Showcase Helm Generator & End2End tests to be documented

**Comment by kuvakina** [comment]
Added Documentation for Helm Generator here https://github.com/LeedsCC/Helm-PHR-Generator

Added Documentation for Helm E2E tests here https://github.com/LeedsCC/Helm-End2End-Tests

Added Documentation for Showcase Generator here https://github.com/PulseTile/PulseTile-React-Showcase-Generator

Added Documentation for Showcase E2E tests here https://github.com/RippleOSI/ShowcaseStack-End2EndTests

**Comment by PhilBarrett** [comment]
Really like these @kuvakina and team, thank you.
