### ISSUE TITLE
Mismatch of created and showed info for Headings

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/Showcase-Project#93]
In details is shown less info, that we create. For example:
**Problems**
![s1.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/72833577-6c6d-4c9e-be5b-2406ed1282df)
![s2.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/da2e86e3-d068-42e9-a54e-6635a800fb21)
**Or Medications**
![s3.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/0775a13a-bcd8-452c-a0bc-70a303e9b5fa)
![s4.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/835b26d9-be1b-44a3-86dd-22b673520b50)

@BogdanScherban could you please take a look? The same for **NODERED-SHOWCASE**

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 
This issue has been done for all plugins. You can see it on the video: 
https://drive.google.com/file/d/1D-76eoMywZdqsBhHDksHxr-iw4YxVe0K/view

**Comment by PhilBarrett** [comment]
Thanks, reviewed and closing
