### ISSUE TITLE
Vitals alsways shows today date

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/Showcase-Project#94]
You can notice in System Info in Details, that Vitals were created in different days, but in the list, it shows today date for all records. 
![s5.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/d1db8434-9911-4fe1-acce-1bcfd5ac3881)
@BogdanScherban @DmitrySolyannik could you take a look, please?

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 
This issue has been done. Now in the table actual dates:
![Screenshot from 2019-07-18 15-38-16](https://user-images.githubusercontent.com/39263134/61457961-2e51f600-a972-11e9-9132-b1ec8b4dadf9.png)
![Screenshot from 2019-07-18 15-38-29](https://user-images.githubusercontent.com/39263134/61457963-2eea8c80-a972-11e9-93e7-a59484b5eb4b.png)

**Comment by PhilBarrett** [comment]
Reviewed and closing, thanks
